week4
jogpfls/likelion12th-web-session3 pull request #3
Opened 2024-04-27 08:17 UTC by jogpfls

2024-05-03 11:26 UTC, constantly-dev reviewed
과제 수고하셨습니다 :)

2024-05-03 17:48 UTC, hyunyeee requested changes
prettier로 코드 포맷팅 해주세요
고생하셨습니다 ~~

2024-05-03 17:48 UTC, hyunyeee commented on src/Login.js
> +    };
id나 pwd 잘못 입력했을 때 input field를 비우면 좋을 것 같아요 ~~

2024-05-03 17:48 UTC, hyunyeee commented on src/App.js
>  }
라우터 사용법 잘못되었기는 한데 아직 안 배운 부분이라 일단 넘어가고 배우고 나서 이 부분 다시 수정 해주세요 ~~

2024-05-09 08:01 UTC, hyunyeee approved these changes

2024-05-09 08:03 UTC, merged